<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <!-- Favicons -->
    <link rel="apple-touch-icon" href="assets/img/apple-icon.png" />
    <link rel="icon" href="assets/img/favicon.png" />
    <title>
        <?= $title ?>
    </title>
    <!--  Arquivos CSS  -->
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet" />
    <link href="assets/css/style.css" rel="stylesheet" type="text/css" />
</head>

<body>
    <section>
        <!--  Todos os arquivos das views serão carregados aqui  -->
        <?php $this->controller->renderView(); ?>
    </section>
    <!--  Arquivos JS  -->
    <script src="assets/js/" type="text/javascript"></script>
</body>

</html>
